FROM resin/%%RESIN_MACHINE_NAME%%-home:3

# install dependencies
RUN apt-get update && apt-get install -yq \
    Adafruit_Python_DHT && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY ./requirements.txt /requirements.txt

